create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  name varchar(100) not null,
  role varchar(40) not null,
  auth_provider varchar(40) not null,
  campus varchar(100),
  email_verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  student_id varchar(50),
  department varchar(100),
  grade varchar(40),
  bio text,
  tech_stack text,
  collaboration_status varchar(20) not null default 'OPEN',
  display_name varchar(80),
  role_tags text[] not null default '{}',
  availability_status varchar(40),
  collaboration_type varchar(80),
  weekly_hours varchar(40),
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null references public.users(id) on delete cascade,
  title varchar(200) not null,
  summary text not null,
  description text,
  project_type varchar(40) not null,
  collaboration_mode varchar(40) not null,
  recruitment_status varchar(40) not null default 'RECRUITING',
  campus varchar(100),
  required_roles text[] not null default '{}',
  tools text[] not null default '{}',
  cover_image_name varchar(255),
  expected_member_count integer,
  start_date date,
  end_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(200) not null,
  description text,
  item_type varchar(40),
  external_url varchar(500),
  role_in_work varchar(100),
  tools text[] not null default '{}',
  cover_image_name varchar(255),
  created_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  applicant_user_id bigint not null references public.users(id) on delete cascade,
  message text,
  application_status varchar(40) not null default 'PENDING',
  target_role varchar(100),
  created_at timestamptz not null default now(),
  constraint applications_project_applicant_unique unique (project_id, applicant_user_id)
);

create index if not exists projects_owner_user_id_idx on public.projects(owner_user_id);
create index if not exists portfolio_items_user_id_idx on public.portfolio_items(user_id);
create index if not exists applications_applicant_user_id_idx on public.applications(applicant_user_id);
