-- Task 6: proposals table, transition RPCs, and matched contact disclosure.
--
-- Status spelling note:
--   applications.application_status uses CANCELED (one L) for compatibility.
--   proposals.proposal_status uses CANCELLED (two L) per MVP plan.

-- ---------------------------------------------------------------------------
-- 1. proposals table
-- ---------------------------------------------------------------------------

create table if not exists public.proposals (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  sender_user_id bigint not null references public.users(id) on delete cascade,
  receiver_user_id bigint not null references public.users(id) on delete cascade,
  message text,
  proposal_status varchar(40) not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint proposals_distinct_users check (sender_user_id <> receiver_user_id),
  constraint proposals_project_sender_receiver_unique
    unique (project_id, sender_user_id, receiver_user_id),
  constraint proposals_proposal_status_check
    check (proposal_status in ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'))
);

create index if not exists proposals_project_id_idx on public.proposals(project_id);
create index if not exists proposals_sender_user_id_idx on public.proposals(sender_user_id);
create index if not exists proposals_receiver_user_id_idx on public.proposals(receiver_user_id);
create index if not exists proposals_proposal_status_idx on public.proposals(proposal_status);

-- ---------------------------------------------------------------------------
-- 2. Privileged transition RPCs
-- ---------------------------------------------------------------------------

create or replace function public.receiver_decide_proposal(
  p_proposal_id bigint,
  p_decision text
)
returns public.proposals
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor bigint;
  v_proposal public.proposals%rowtype;
begin
  v_actor := public.current_app_user_id();

  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  if p_decision not in ('ACCEPTED', 'REJECTED') then
    raise exception 'INVALID_DECISION';
  end if;

  select *
  into v_proposal
  from public.proposals
  where id = p_proposal_id
    and receiver_user_id = v_actor
  for update;

  if not found then
    raise exception 'NOT_FOUND_OR_FORBIDDEN';
  end if;

  if v_proposal.proposal_status <> 'PENDING' then
    raise exception 'INVALID_TRANSITION';
  end if;

  update public.proposals
  set
    proposal_status = p_decision,
    updated_at = now()
  where id = p_proposal_id
  returning * into v_proposal;

  return v_proposal;
end;
$$;

create or replace function public.sender_cancel_proposal(
  p_proposal_id bigint
)
returns public.proposals
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor bigint;
  v_proposal public.proposals%rowtype;
begin
  v_actor := public.current_app_user_id();

  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  select *
  into v_proposal
  from public.proposals
  where id = p_proposal_id
    and sender_user_id = v_actor
  for update;

  if not found then
    raise exception 'NOT_FOUND_OR_FORBIDDEN';
  end if;

  if v_proposal.proposal_status <> 'PENDING' then
    raise exception 'INVALID_TRANSITION';
  end if;

  update public.proposals
  set
    proposal_status = 'CANCELLED',
    updated_at = now()
  where id = p_proposal_id
  returning * into v_proposal;

  return v_proposal;
end;
$$;

create or replace function public.get_matched_contact_details(
  p_other_user_id bigint
)
returns table (
  user_id bigint,
  email text,
  name text,
  campus text,
  department text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor bigint;
begin
  v_actor := public.current_app_user_id();

  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  if p_other_user_id is null or p_other_user_id = v_actor then
    raise exception 'VALIDATION_ERROR';
  end if;

  if not exists (
    select 1
    from public.applications as a
    inner join public.projects as p on p.id = a.project_id
    where a.application_status = 'ACCEPTED'
      and (
        (p.owner_user_id = v_actor and a.applicant_user_id = p_other_user_id)
        or (p.owner_user_id = p_other_user_id and a.applicant_user_id = v_actor)
      )
  )
  and not exists (
    select 1
    from public.proposals as pr
    where pr.proposal_status = 'ACCEPTED'
      and (
        (pr.sender_user_id = v_actor and pr.receiver_user_id = p_other_user_id)
        or (pr.sender_user_id = p_other_user_id and pr.receiver_user_id = v_actor)
      )
  ) then
    raise exception 'NOT_FOUND_OR_FORBIDDEN';
  end if;

  return query
  select
    u.id,
    u.email::text,
    u.name::text,
    u.campus::text,
    coalesce(p.department, '')::text
  from public.users as u
  left join public.profiles as p on p.user_id = u.id
  where u.id = p_other_user_id;
end;
$$;

revoke all on function public.receiver_decide_proposal(bigint, text) from public;
revoke all on function public.sender_cancel_proposal(bigint) from public;
revoke all on function public.get_matched_contact_details(bigint) from public;

grant execute on function public.receiver_decide_proposal(bigint, text) to authenticated, service_role;
grant execute on function public.sender_cancel_proposal(bigint) to authenticated, service_role;
grant execute on function public.get_matched_contact_details(bigint) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. RLS
-- ---------------------------------------------------------------------------

alter table public.proposals enable row level security;

create policy proposals_insert_sender_pending
  on public.proposals
  for insert
  to authenticated
  with check (
    sender_user_id = public.current_app_user_id()
    and proposal_status = 'PENDING'
    and exists (
      select 1
      from public.projects as p
      where p.id = project_id
        and p.owner_user_id = public.current_app_user_id()
        and p.recruitment_status = 'RECRUITING'
    )
  );

create policy proposals_select_sender
  on public.proposals
  for select
  to authenticated
  using (sender_user_id = public.current_app_user_id());

create policy proposals_select_receiver
  on public.proposals
  for select
  to authenticated
  using (receiver_user_id = public.current_app_user_id());

-- No direct UPDATE policy: transitions go through receiver_decide_proposal()
-- and sender_cancel_proposal().
