server.port=8080

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug

supabase.url=${SUPABASE_URL}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
