server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/campus_link}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug

supabase.url=${SUPABASE_URL:}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY:}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:}
